CREATE TABLE IF NOT EXISTS `anti_channeling_rules` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `rule_code` VARCHAR(64) NOT NULL,
  `rule_name` VARCHAR(128) NOT NULL,
  `rule_type` VARCHAR(64) NOT NULL,
  `enabled` TINYINT(1) NOT NULL DEFAULT 1,
  `severity` INT NOT NULL DEFAULT 2,
  `threshold` INT NULL,
  `window_seconds` INT NULL,
  `config` JSON NULL,
  `notify_channels` JSON NULL,
  `description` VARCHAR(255) NULL,
  `status` INT NOT NULL DEFAULT 1,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `anti_channeling_rules_rule_code_key` (`rule_code`),
  KEY `anti_channeling_rules_rule_type_idx` (`rule_type`),
  KEY `anti_channeling_rules_enabled_status_idx` (`enabled`, `status`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `anti_channeling_alerts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `alert_no` VARCHAR(64) NOT NULL,
  `alert_type` VARCHAR(64) NOT NULL,
  `severity` INT NOT NULL DEFAULT 2,
  `title` VARCHAR(255) NULL,
  `code` VARCHAR(128) NULL,
  `box_no` VARCHAR(128) NULL,
  `shipment_no` VARCHAR(128) NULL,
  `product_id` INT NULL,
  `product_code` VARCHAR(64) NULL,
  `product_name` VARCHAR(128) NULL,
  `agent_id` INT NULL,
  `agent_name` VARCHAR(128) NULL,
  `authorized_region` VARCHAR(255) NULL,
  `authorized_province` VARCHAR(64) NULL,
  `authorized_city` VARCHAR(64) NULL,
  `actual_location` VARCHAR(255) NULL,
  `actual_province` VARCHAR(64) NULL,
  `actual_city` VARCHAR(64) NULL,
  `ip` VARCHAR(64) NULL,
  `device_id` VARCHAR(128) NULL,
  `user_agent` VARCHAR(512) NULL,
  `scan_time` DATETIME(3) NULL,
  `first_seen_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `last_seen_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `evidence` JSON NULL,
  `notification_channels` JSON NULL,
  `status` INT NOT NULL DEFAULT 0,
  `handle_result` VARCHAR(255) NULL,
  `handled_by` INT NULL,
  `handled_at` DATETIME(3) NULL,
  `remark` VARCHAR(255) NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `anti_channeling_alerts_alert_no_key` (`alert_no`),
  KEY `anti_channeling_alerts_alert_type_idx` (`alert_type`),
  KEY `anti_channeling_alerts_severity_idx` (`severity`),
  KEY `anti_channeling_alerts_status_idx` (`status`),
  KEY `anti_channeling_alerts_code_idx` (`code`),
  KEY `anti_channeling_alerts_box_no_idx` (`box_no`),
  KEY `anti_channeling_alerts_shipment_no_idx` (`shipment_no`),
  KEY `anti_channeling_alerts_agent_id_idx` (`agent_id`),
  KEY `anti_channeling_alerts_actual_province_actual_city_idx` (`actual_province`, `actual_city`),
  KEY `anti_channeling_alerts_created_at_idx` (`created_at`),
  KEY `anti_channeling_alerts_last_seen_at_idx` (`last_seen_at`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `anti_channeling_notifications` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `alert_id` INT NOT NULL,
  `channel` VARCHAR(32) NOT NULL,
  `receiver` VARCHAR(128) NULL,
  `target` VARCHAR(255) NULL,
  `status` INT NOT NULL DEFAULT 0,
  `payload` JSON NULL,
  `error` VARCHAR(255) NULL,
  `sent_at` DATETIME(3) NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  KEY `anti_channeling_notifications_alert_id_idx` (`alert_id`),
  KEY `anti_channeling_notifications_channel_idx` (`channel`),
  KEY `anti_channeling_notifications_status_idx` (`status`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

INSERT IGNORE INTO `anti_channeling_rules` (`rule_code`, `rule_name`, `rule_type`, `enabled`, `severity`, `threshold`, `window_seconds`, `notify_channels`, `description`, `status`) VALUES
('geo_mismatch', '扫码位置与授权区域不符', 'geofence', 1, 3, 1, 3600, JSON_ARRAY('system','app','sms'), '授权广州销售的单品在深圳等非授权区域被扫码时触发预警。', 1),
('same_code_multi_region', '同一编码短时间异地扫码', 'cross_region_scan', 1, 4, 2, 3600, JSON_ARRAY('system','app','sms'), '同一码在窗口期内出现在两个及以上不同省市时触发。', 1),
('ip_high_frequency', '同一 IP 短时高频扫码', 'behavior', 1, 2, 30, 60, JSON_ARRAY('system','app'), '同一 IP 在短时间内大量访问查询接口时触发。', 1),
('device_risk', '越狱/Root/自动化设备访问', 'device', 1, 3, 1, 3600, JSON_ARRAY('system','app'), '识别 UA、设备完整性参数或客户端标记中的越狱、Root、Hook、自动化访问风险。', 1),
('shipment_region_mismatch', '经销商跨区域调拨/出库位置异常', 'shipment', 1, 4, 1, 86400, JSON_ARRAY('system','app','sms'), '发货/调拨目的地与代理商授权区域或箱内编码授权区域不符时触发。', 1),
('fake_code_scan', '无效码/假码扫码', 'anti_fake', 1, 2, 1, 3600, JSON_ARRAY('system'), '消费者查询到不存在、注销、锁定或过期编码时留存异常证据。', 1);
