CREATE TABLE IF NOT EXISTS `manufacturers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `manufacturer_code` VARCHAR(64) NULL,
  `manufacturer_name` VARCHAR(128) NOT NULL,
  `company_name` VARCHAR(128) NULL,
  `social_credit_code` VARCHAR(128) NULL,
  `legal_person` VARCHAR(64) NULL,
  `contact_name` VARCHAR(64) NULL,
  `contact_phone` VARCHAR(32) NULL,
  `contact_email` VARCHAR(128) NULL,
  `province` VARCHAR(64) NULL,
  `city` VARCHAR(64) NULL,
  `address` VARCHAR(255) NULL,
  `business_license` VARCHAR(255) NULL,
  `production_license` VARCHAR(128) NULL,
  `quality_report` JSON NULL,
  `status` INT NOT NULL DEFAULT 1,
  `remark` TEXT NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `manufacturers_manufacturer_code_key` (`manufacturer_code`),
  INDEX `manufacturers_status_idx` (`status`),
  INDEX `manufacturers_manufacturer_name_idx` (`manufacturer_name`),
  INDEX `manufacturers_company_name_idx` (`company_name`),
  INDEX `manufacturers_province_city_idx` (`province`, `city`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
