CREATE TABLE IF NOT EXISTS `channel_authorizations` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `agent_id` INT NULL,
  `agent_code` VARCHAR(64) NULL,
  `agent_name` VARCHAR(128) NULL,
  `channel_type` VARCHAR(64) NULL,
  `channel_level` VARCHAR(64) NULL,
  `province_name` VARCHAR(64) NULL,
  `city_name` VARCHAR(64) NULL,
  `district_name` VARCHAR(64) NULL,
  `region_group` VARCHAR(255) NULL,
  `valid_from` DATE NULL,
  `valid_to` DATE NULL,
  `approval_status` VARCHAR(64) NULL DEFAULT 'active',
  `allow_online` TINYINT(1) NOT NULL DEFAULT 0,
  `allow_wholesale` TINYINT(1) NOT NULL DEFAULT 0,
  `rules` JSON NULL,
  `status` INT NOT NULL DEFAULT 1,
  `remark` VARCHAR(255) NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  KEY `channel_authorizations_agent_id_idx` (`agent_id`),
  KEY `channel_authorizations_channel_type_idx` (`channel_type`),
  KEY `channel_authorizations_province_city_idx` (`province_name`, `city_name`),
  KEY `channel_authorizations_valid_idx` (`valid_from`, `valid_to`),
  KEY `channel_authorizations_status_idx` (`status`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `product_channel_bindings` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `binding_no` VARCHAR(64) NOT NULL,
  `scope_type` VARCHAR(32) NOT NULL,
  `product_id` INT NULL,
  `product_code` VARCHAR(64) NULL,
  `product_name` VARCHAR(128) NULL,
  `sku_code` VARCHAR(64) NULL,
  `batch_no` VARCHAR(64) NULL,
  `code` VARCHAR(128) NULL,
  `box_no` VARCHAR(128) NULL,
  `agent_id` INT NULL,
  `agent_name` VARCHAR(128) NULL,
  `province_name` VARCHAR(64) NULL,
  `city_name` VARCHAR(64) NULL,
  `district_name` VARCHAR(64) NULL,
  `region_group` VARCHAR(255) NULL,
  `channel_type` VARCHAR(64) NULL,
  `channel_policy` JSON NULL,
  `locked` TINYINT(1) NOT NULL DEFAULT 1,
  `source_scene` VARCHAR(64) NULL,
  `source_ref` VARCHAR(128) NULL,
  `created_by` INT NULL,
  `status` INT NOT NULL DEFAULT 1,
  `remark` VARCHAR(255) NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `product_channel_bindings_binding_no_key` (`binding_no`),
  KEY `product_channel_bindings_scope_idx` (`scope_type`),
  KEY `product_channel_bindings_product_id_idx` (`product_id`),
  KEY `product_channel_bindings_product_batch_idx` (`product_code`, `batch_no`),
  KEY `product_channel_bindings_code_idx` (`code`),
  KEY `product_channel_bindings_box_no_idx` (`box_no`),
  KEY `product_channel_bindings_agent_id_idx` (`agent_id`),
  KEY `product_channel_bindings_province_city_idx` (`province_name`, `city_name`),
  KEY `product_channel_bindings_status_idx` (`status`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `anti_channeling_exemptions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `transfer_no` VARCHAR(64) NOT NULL,
  `source_agent_id` INT NULL,
  `source_agent_name` VARCHAR(128) NULL,
  `source_region` VARCHAR(255) NULL,
  `source_province` VARCHAR(64) NULL,
  `source_city` VARCHAR(64) NULL,
  `target_agent_id` INT NULL,
  `target_agent_name` VARCHAR(128) NULL,
  `target_region` VARCHAR(255) NULL,
  `target_province` VARCHAR(64) NULL,
  `target_city` VARCHAR(64) NULL,
  `codes` JSON NULL,
  `box_nos` JSON NULL,
  `shipment_no` VARCHAR(128) NULL,
  `valid_from` DATETIME(3) NULL,
  `valid_to` DATETIME(3) NULL,
  `reason` VARCHAR(255) NULL,
  `approval_no` VARCHAR(64) NULL,
  `approved_by` INT NULL,
  `created_by` INT NULL,
  `used_count` INT NOT NULL DEFAULT 0,
  `last_used_at` DATETIME(3) NULL,
  `evidence` JSON NULL,
  `status` INT NOT NULL DEFAULT 1,
  `remark` VARCHAR(255) NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `anti_channeling_exemptions_transfer_no_key` (`transfer_no`),
  KEY `anti_channeling_exemptions_target_agent_idx` (`target_agent_id`),
  KEY `anti_channeling_exemptions_target_region_idx` (`target_province`, `target_city`),
  KEY `anti_channeling_exemptions_valid_idx` (`valid_from`, `valid_to`),
  KEY `anti_channeling_exemptions_status_idx` (`status`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `anti_channeling_flow_logs` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `log_no` VARCHAR(64) NOT NULL,
  `scene` VARCHAR(64) NOT NULL,
  `action` VARCHAR(64) NULL,
  `code` VARCHAR(128) NULL,
  `box_no` VARCHAR(128) NULL,
  `shipment_no` VARCHAR(128) NULL,
  `product_id` INT NULL,
  `product_code` VARCHAR(64) NULL,
  `product_name` VARCHAR(128) NULL,
  `batch_no` VARCHAR(64) NULL,
  `agent_id` INT NULL,
  `agent_name` VARCHAR(128) NULL,
  `store_id` INT NULL,
  `store_name` VARCHAR(128) NULL,
  `channel_type` VARCHAR(64) NULL,
  `authorized_region` VARCHAR(255) NULL,
  `authorized_province` VARCHAR(64) NULL,
  `authorized_city` VARCHAR(64) NULL,
  `actual_location` VARCHAR(255) NULL,
  `actual_province` VARCHAR(64) NULL,
  `actual_city` VARCHAR(64) NULL,
  `decision` VARCHAR(32) NOT NULL DEFAULT 'pass',
  `reason` VARCHAR(255) NULL,
  `operator_id` INT NULL,
  `operator_name` VARCHAR(128) NULL,
  `device_id` VARCHAR(128) NULL,
  `ip` VARCHAR(64) NULL,
  `user_agent` VARCHAR(512) NULL,
  `exemption_id` INT NULL,
  `alert_id` INT NULL,
  `evidence` JSON NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `anti_channeling_flow_logs_log_no_key` (`log_no`),
  KEY `anti_channeling_flow_logs_scene_idx` (`scene`),
  KEY `anti_channeling_flow_logs_decision_idx` (`decision`),
  KEY `anti_channeling_flow_logs_code_idx` (`code`),
  KEY `anti_channeling_flow_logs_box_no_idx` (`box_no`),
  KEY `anti_channeling_flow_logs_shipment_no_idx` (`shipment_no`),
  KEY `anti_channeling_flow_logs_agent_id_idx` (`agent_id`),
  KEY `anti_channeling_flow_logs_actual_region_idx` (`actual_province`, `actual_city`),
  KEY `anti_channeling_flow_logs_created_at_idx` (`created_at`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

INSERT IGNORE INTO `anti_channeling_rules` (`rule_code`, `rule_name`, `rule_type`, `enabled`, `severity`, `threshold`, `window_seconds`, `notify_channels`, `description`, `status`) VALUES
('outbound_region_mismatch', '出库发货区域/渠道不匹配', 'flow_outbound', 1, 5, 1, 86400, JSON_ARRAY('system','app','sms'), '仓库出库时收货区域或经销商与商品授权区域不一致，默认阻断出库。', 1),
('inbound_region_mismatch', '渠道入库区域/门店不匹配', 'flow_inbound', 1, 4, 1, 86400, JSON_ARRAY('system','app','sms'), '经销商或门店收货入库与商品授权区域不一致，默认禁止入库并生成工单。', 1),
('sale_region_mismatch', '终端售卖区域不匹配', 'flow_sale', 1, 5, 1, 86400, JSON_ARRAY('system','app','sms'), '门店销售核销区域与商品授权区域不一致，默认禁止下单核销。', 1),
('consumer_geo_mismatch', '消费者扫码地域异常', 'flow_consumer', 1, 3, 1, 86400, JSON_ARRAY('system','app'), '消费者扫码地域与授权售卖区域不一致，后台留证预警，消费者端不展示窜货原因。', 1),
('unauthorized_channel', '未授权渠道/授权过期', 'channel', 1, 4, 1, 86400, JSON_ARRAY('system','app','sms'), '扫码主体没有有效渠道授权或授权已过期。', 1);
