-- 装箱码归属与防伪码级联字段：产品、公司、地区、代理商全字段沉淀到箱码与防伪码。
ALTER TABLE `boxes`
  ADD COLUMN `product_code` VARCHAR(64) NULL COMMENT '产品编号快照',
  ADD COLUMN `product_name` VARCHAR(128) NULL COMMENT '产品名称快照',
  ADD COLUMN `category` VARCHAR(64) NULL COMMENT '产品分类快照',
  ADD COLUMN `brand` VARCHAR(64) NULL COMMENT '品牌快照',
  ADD COLUMN `specification` VARCHAR(128) NULL COMMENT '规格快照',
  ADD COLUMN `unit` VARCHAR(32) NULL COMMENT '单位快照',
  ADD COLUMN `production_place` VARCHAR(128) NULL COMMENT '生成/生产地点快照',
  ADD COLUMN `manufacturer` VARCHAR(128) NULL COMMENT '制造商/公司快照',
  ADD COLUMN `province_code` VARCHAR(16) NULL COMMENT '省份编码',
  ADD COLUMN `city_code` VARCHAR(16) NULL COMMENT '城市编码',
  ADD COLUMN `province_name` VARCHAR(64) NULL COMMENT '省份名称',
  ADD COLUMN `city_name` VARCHAR(64) NULL COMMENT '城市名称',
  ADD COLUMN `region_group` VARCHAR(128) NULL COMMENT '区域分组',
  ADD COLUMN `warehouse` VARCHAR(128) NULL COMMENT '仓库',
  ADD COLUMN `distributor` VARCHAR(128) NULL COMMENT '经销商/渠道',
  ADD COLUMN `agent_id` INT NULL COMMENT '代理商ID',
  ADD COLUMN `agent_name` VARCHAR(128) NULL COMMENT '代理商名称快照',
  ADD COLUMN `company_name` VARCHAR(128) NULL COMMENT '归属公司名称',
  ADD COLUMN `ownership_at` DATETIME NULL COMMENT '最近一次归属变更时间',
  ADD INDEX `boxes_product_code_idx` (`product_code`),
  ADD INDEX `boxes_province_name_city_name_idx` (`province_name`, `city_name`),
  ADD INDEX `boxes_agent_id_idx` (`agent_id`);

ALTER TABLE `anti_fake_codes`
  ADD COLUMN `box_id` INT NULL COMMENT '所属装箱ID',
  ADD COLUMN `box_no` VARCHAR(128) NULL COMMENT '所属装箱码',
  ADD COLUMN `product_code` VARCHAR(64) NULL COMMENT '产品编号快照',
  ADD COLUMN `product_name` VARCHAR(128) NULL COMMENT '产品名称快照',
  ADD COLUMN `category` VARCHAR(64) NULL COMMENT '产品分类快照',
  ADD COLUMN `brand` VARCHAR(64) NULL COMMENT '品牌快照',
  ADD COLUMN `specification` VARCHAR(128) NULL COMMENT '规格快照',
  ADD COLUMN `unit` VARCHAR(32) NULL COMMENT '单位快照',
  ADD COLUMN `production_place` VARCHAR(128) NULL COMMENT '生成/生产地点快照',
  ADD COLUMN `manufacturer` VARCHAR(128) NULL COMMENT '制造商/公司快照',
  ADD COLUMN `province_code` VARCHAR(16) NULL COMMENT '省份编码',
  ADD COLUMN `city_code` VARCHAR(16) NULL COMMENT '城市编码',
  ADD COLUMN `province_name` VARCHAR(64) NULL COMMENT '省份名称',
  ADD COLUMN `city_name` VARCHAR(64) NULL COMMENT '城市名称',
  ADD COLUMN `region_group` VARCHAR(128) NULL COMMENT '区域分组',
  ADD COLUMN `warehouse` VARCHAR(128) NULL COMMENT '仓库',
  ADD COLUMN `distributor` VARCHAR(128) NULL COMMENT '经销商/渠道',
  ADD COLUMN `agent_id` INT NULL COMMENT '代理商ID',
  ADD COLUMN `agent_name` VARCHAR(128) NULL COMMENT '代理商名称快照',
  ADD COLUMN `company_name` VARCHAR(128) NULL COMMENT '归属公司名称',
  ADD COLUMN `box_bound_at` DATETIME NULL COMMENT '装箱绑定时间',
  ADD COLUMN `ownership_at` DATETIME NULL COMMENT '最近一次归属变更时间',
  ADD INDEX `anti_fake_codes_box_id_idx` (`box_id`),
  ADD INDEX `anti_fake_codes_box_no_idx` (`box_no`),
  ADD INDEX `anti_fake_codes_product_code_idx` (`product_code`),
  ADD INDEX `anti_fake_codes_manufacturer_idx` (`manufacturer`),
  ADD INDEX `anti_fake_codes_province_name_city_name_idx` (`province_name`, `city_name`),
  ADD INDEX `anti_fake_codes_agent_id_idx` (`agent_id`);
